name: Large Collection
version: "1.0"
description: Allow editors to search or find articles within large collections.
url: https://abigah.com/plugins/large_collection
developer: Abigah
developer_url: https://abigah.com
